version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html   # Adjust the destination path based on your application structure

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh   # Path to your custom scripts
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/after_install.sh    # Path to your custom scripts
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/application_start.sh   # Path to your custom scripts
      timeout: 300
      runas: ec2-user
